### PR TITLE
addition of xsummarize_alignments

### PR DESCRIPTION
**Pull request by vpbrendel**
The new script nicely pulls data out of the various log files to summarize what happened to the input reads along the way ....

### CODE REVIEW

**Comment by rpolicastro** [comment]
I ran xsummarize_alignments after running xgetstarted1 and 2, and the tsv it created had no numbers for each processing step. The xgetstarted scripts worked.

**Comment by vpbrendel** [comment]
Of course. xummarize_alignments will only work after alignments have been created, as per xgetstarted3 instructions (ie, following the steps in yeast/0Record and human/0Record).

**Comment by rpolicastro** [comment]
Alright, I went through the additional steps starting from xgetstarted3, and downloaded the fastq files from box. It's running GoSTRIPEs on everything now. I'll report back on the status when it's finished.

**Comment by rpolicastro** [comment]
Got it working with the yeast data for the paper. Accepting the pull request.

**Pull request merged**
